# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '11.x'
    displayName: 'Install Node.js'

  - script: |
      yarn
      yarn lint
      docker run -d -p 5678:5678 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=williemayshayes postgres
      yarn test
    displayName: 'Install and test'
