name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12.10-slim
    services:
      db:
        image: postgres
        ports: 5432/tcp
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: williemayshayes
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
